# Example of how to use lightcurve class

#### Import the Lightcurve module from MALT

In [1]:
from malt import Lightcurve
import os
import numpy as np

/usr/local/lib/python3.6/dist-packages/tqdm/autonotebook/__init__.py:14: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  " (e.g. in jupyter console)", TqdmExperimentalWarning)


#### Get a list of all data files

In [4]:
root = 'example_data/'
allfiles = []
for path, subdirs, files in os.walk(root):
    for filename in files:
        f = os.path.join(path, filename)
        allfiles.append(f)

#### Choose a random file to make a Lightcurve object

In [5]:
rand_num = np.random.randint(len(allfiles))
test_file = allfiles[rand_num]

#### For now we will leave all the parameters as defaults, for more on how to change the parameters see Notebook on how to use the Dataset object

In [7]:
test_lightcurve = Lightcurve(test_file)

#### We can now have a look at all the atributes of this Lightcurve object 

In [11]:
print('Filename: ',test_lightcurve.filename)
print('Type: ', test_lightcurve.type)
print('RA and DEC: ', test_lightcurve.ra_dec)

Filename:  B0605-085
Type:  AGN
RA and DEC:  0


#### We can also have a look at the data about the object i.e the time, flux and flux err

In [13]:
test_lightcurve.time

array([ 911.68068165,  952.10162692,  963.14344611,  991.60391433,
       1000.67846136, 1047.73166815, 1083.49210531, 1085.10535812,
       1086.71861092, 1095.59150134, 1132.15856491, 1133.77181771,
       1141.65883142, 1147.0542658 , 1188.28631872, 1190.30288473,
       1206.63706937, 1226.96405471, 1235.13786891, 1264.84860806,
       1269.68836647, 1271.52568217, 1273.13893497, 1274.39368715,
       1302.35673576, 1305.04549043, 1306.92761871, 1311.09518845,
       1331.0591919 , 1402.82653541, 1404.43978821, 1406.05304101,
       1409.26162159, 1421.19969234, 1451.492995  , 1452.79255976,
       1532.69338615, 1534.30663896, 1535.91989176, 1537.53314457,
       1543.80690547, 1553.01589023, 1584.67597651, 1593.75052354,
       1633.61131158, 1635.13493923, 1646.38289628, 1676.00401027,
       1680.71829346, 1682.00889571, 1685.03374471, 1714.99095304,
       1716.42495553, 1734.97736278, 1774.3945063 , 1807.57373897,
       1811.51724583, 1814.45695094, 1847.90505908, 1854.62694

In [14]:
test_lightcurve.flux

array([2.77998171, 2.90121618, 2.82018051, 2.66512801, 2.732126  ,
       2.6172723 , 2.90440656, 2.84697971, 2.78955286, 2.47370517,
       2.732126  , 2.67469915, 2.39394565, 2.51390396, 2.29424625,
       2.61248673, 2.88909273, 2.78955286, 2.18657091, 2.68905586,
       2.51677531, 2.4513725 , 2.39394565, 2.34928032, 2.9139777 ,
       2.81826628, 2.75126829, 2.60291559, 2.28228233, 2.45775326,
       2.40032641, 2.34289956, 2.54070316, 2.19374926, 2.28547271,
       2.23921219, 2.51518012, 2.45775326, 2.40032641, 2.34289956,
       2.11957291, 2.18178534, 2.22485547, 2.29185347, 2.04300378,
       1.9887673 , 2.36842261, 2.09404987, 1.92623584, 1.88029436,
       2.16264305, 2.26633042, 2.21528433, 2.33492361, 2.02386149,
       2.09085949, 1.95048274, 2.15785748, 2.21528433, 2.28802501,
       2.1387152 , 2.08128834, 1.97600578, 2.02864706, 2.31482421,
       2.18417812, 2.00471921, 2.19135648, 2.12595367, 2.06852682,
       2.3038174 , 1.97600578, 2.42584946, 2.06932442, 2.24718

In [15]:
test_lightcurve.flux_err

array([0.13899909, 0.14506081, 0.14100903, 0.1332564 , 0.1366063 ,
       0.13086361, 0.14522033, 0.14234899, 0.13947764, 0.12368526,
       0.1366063 , 0.13373496, 0.11969728, 0.1256952 , 0.11471231,
       0.13062434, 0.14445464, 0.13947764, 0.10932855, 0.13445279,
       0.12583877, 0.12256863, 0.11969728, 0.11746402, 0.14569889,
       0.14091331, 0.13756341, 0.13014578, 0.11411412, 0.12288766,
       0.12001632, 0.11714498, 0.12703516, 0.10968746, 0.11427364,
       0.11196061, 0.12575901, 0.12288766, 0.12001632, 0.11714498,
       0.10597865, 0.10908927, 0.11124277, 0.11459267, 0.10215019,
       0.09943837, 0.11842113, 0.10470249, 0.09631179, 0.09401472,
       0.10813215, 0.11331652, 0.11076422, 0.11674618, 0.10119307,
       0.10454297, 0.09752414, 0.10789287, 0.11076422, 0.11440125,
       0.10693576, 0.10406442, 0.09880029, 0.10143235, 0.11574121,
       0.10920891, 0.10023596, 0.10956782, 0.10629768, 0.10342634,
       0.11519087, 0.09880029, 0.12129247, 0.10346622, 0.11235

#### The Lightcurve object also has methods that allow you to interpolate the flux data and extract features. We will be using the defaults here (Gaussian processes for intepolation and wavelet feature extraction) however, different methods can be chosen by the user.

In [17]:
test_lightcurve.interpolate()
test_lightcurve.extract_features()

#### We can now check the new attributes that we have just created.

In [18]:
test_lightcurve.interp_flux

array([[2.00411206, 2.00410926, 2.0041066 , 2.0041039 , 2.00410116,
        2.00409858, 2.00409588, 2.00409298, 2.00409033, 2.00408769,
        2.00408498, 2.00408227, 2.00407963, 2.00407675, 2.00407409,
        2.00407137, 2.00406874, 2.00406599, 2.00406325, 2.00406059,
        2.00405788, 2.00405514, 2.00405243, 2.00404979, 2.00404713,
        2.00404427, 2.00404162, 2.00403898, 2.00403614, 2.00403354,
        2.00403083, 2.00402807, 2.0040254 , 2.00402271, 2.00402004,
        2.00401727, 2.00401466, 2.00401184, 2.00400908, 2.00400636,
        2.00400377, 2.00400108, 2.00399825, 2.00399561, 2.00399282,
        2.00399009, 2.00398751, 2.00398476, 2.00398203, 2.00397938,
        2.00397665, 2.00397397, 2.00397128, 2.00396854, 2.00396577,
        2.00396312, 2.00396046, 2.00395772, 2.0039551 , 2.00395226,
        2.00394966, 2.00394685, 2.00394412, 2.00394157, 2.00393872,
        2.00393601, 2.00393336, 2.00393069, 2.00392788, 2.00392519,
        2.00392252, 2.00391981, 2.00391706, 2.00

In [19]:
test_lightcurve.features

array([[ 4.00791885e+00,  4.00805204e+00,  4.00815599e+00,
         4.00821374e+00,  4.00820834e+00,  4.00820298e+00,
         4.00819757e+00,  4.00819210e+00,  4.00818667e+00,
         4.00818127e+00,  4.00817586e+00,  4.00817049e+00,
         4.00816508e+00,  4.00815961e+00,  4.00815417e+00,
         4.00814872e+00,  4.00814332e+00,  4.00813792e+00,
         4.00813251e+00,  4.00812709e+00,  4.00812166e+00,
         4.00811626e+00,  4.00811085e+00,  4.00810547e+00,
         4.00810008e+00,  4.00809463e+00,  4.00808922e+00,
         4.00808380e+00,  4.00807835e+00,  4.00807296e+00,
         4.00806755e+00,  4.00806213e+00,  4.00805674e+00,
         4.00805135e+00,  4.00804598e+00,  4.00804057e+00,
         4.00803515e+00,  4.00802968e+00,  4.00802422e+00,
         4.00801878e+00,  4.00801339e+00,  4.00800800e+00,
         4.00800255e+00,  4.00799713e+00,  4.00799166e+00,
         4.00798622e+00,  4.00798084e+00,  4.00797543e+00,
         4.00797004e+00,  4.00796466e+00,  4.00795926e+0

### The Lightcurve object was not created to be used alone but rather in conjuction with the Dataset object. For more on the Dataset object see the Notebook in Examples.